export const SHOW_VINYLS = 'SHOW_VINYLS'
export const SHOW_VINYL = 'SHOW_VINYL'
export const ADD_VINYL = 'ADD_VINYL '
export const EDIT_VINYL = 'EDIT_VINYL'
export const DELETE_VINYL = 'DELETE_VINYL'
export const GET_CURRENT_USER = 'GET_CURRENT_USER'